add compose and ci test
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -58,3 +58,32 @@ jobs:
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
+
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: docker/setup-qemu-action@v2
+      - uses: docker/setup-buildx-action@2dd22fa31c04297d369158eb483250f578504a9f
+
+      - name: Start containers
+        run: docker-compose up --build --force-recreate --detach
+
+      - name: Run Tests
+        run: |
+          set -x
+          name=$(docker-compose ps | grep device | awk '{print $1}')
+          rc=$(docker wait "${name}")
+          if [ "${rc}" != "0" ]; then
+              echo "device failed:"
+              docker logs "${name}"
+              exit 1
+          fi
+
+      - name: Logs
+        if: always()
+        run: docker-compose logs
+
+      - name: Stop containers
+        if: always()
+        run: docker-compose down --volumes --remove-orphans
